config/urls.py
from django.conf import settings

from django.urls import re_path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

# Import feeds
import core.views
from events.feeds import EventFeed, feedview
import events.reports
import events.views
from ligoauth.views import (
    manage_password, ShibLoginView, ShibPostLoginView
)
import search.views

# Django admin auto-discover
admin.autodiscover()

feeds = {
    'latest' : EventFeed
}


urlpatterns = [
    re_path(r'^$', events.views.index, name="home"),
    re_path(r'^navbar_only$', TemplateView.as_view(
        template_name='navbar_only.html'), name="navbar-only"),
    re_path(r'^SPInfo', TemplateView.as_view(template_name='gracedb/spinfo.html'),
         name="spinfo"),
    re_path(r'^SPPrivacy', TemplateView.as_view(
        template_name='gracedb/spprivacy.html'), name="spprivacy"),
    re_path(r'^DiscoveryService', TemplateView.as_view(
        template_name='discovery.html'), name="discovery"),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^superevents/', include('superevents.urls')),
    re_path(r'^alerts/', include('alerts.urls')),
    re_path(r'^feeds/(?P<url>.*)/$', EventFeed()),
    re_path(r'^feeds/$', feedview, name="feeds"),

    re_path(r'^other/$', TemplateView.as_view(template_name='other.html'),
        name='other'),
    re_path(r'^performance/$', events.views.performance, name="performance"),
    re_path(r'^reports/$', events.reports.reports_page_context, name="reports"),
    re_path(r'^latest/$', search.views.latest, name="latest"),
    #(r'^reports/(?P<path>.+)$', 'django.views.static.serve',
    #        {'document_root': settings.LATENCY_REPORT_DEST_DIR}),
    re_path(r'^search/$', search.views.search, name="mainsearch"),

    # Authentication
    re_path(r'^login/$', ShibLoginView.as_view(), name='login'),
    re_path(r'^post-login/$', ShibPostLoginView.as_view(), name='post-login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Password management
    re_path('^manage-password/$', manage_password, name='manage-password'),

    # API URLs
    re_path(r'^api/', include('api.urls')),
    # Legacy API URLs - must be maintained!
    re_path(r'^apibasic/', include('api.urls', namespace='legacy_apibasic')),
    re_path(r'^apiweb/', include('api.urls', namespace='legacy_apiweb')),

    # Heartbeat URL
    re_path(r'^heartbeat/$', core.views.heartbeat, name='heartbeat'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),

    # Sessions
    re_path(r'^', include('user_sessions.urls', 'user_sessions')),

]

# We don't require settings.DEBUG for django-silk since running unit tests
# by default setings settings.DEBUG to False, unless you use the
# --debug-mode flag
if ('silk' in settings.INSTALLED_APPS):
    # Add django-silk
    urlpatterns = [
        re_path(r'^silk/', include('silk.urls', namespace='silk'))
    ] + urlpatterns

# Add django-debug-toolbar
if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

gracedb/api/urls.py
from django.urls import re_path, include

from .v1 import urls as v1_urls
from .v2 import urls as v2_urls

app_name = 'api'

urlpatterns = [
    re_path(r'^', include((v1_urls, 'default'))),
    re_path(r'^v1/', include((v1_urls, 'v1'))),
    re_path(r'^v2/', include((v2_urls, 'v2'))),
]

gracedb/core/urls.py
# URL utilities

from django.contrib.sites.models import Site


def build_absolute_uri(relative_uri, request=None):
    if request is not None:
        return request.build_absolute_uri(relative_uri)
    else:
        # Assume HTTPS
        domain = Site.objects.get_current().domain
        return 'https://' + domain + relative_uri

# A helper function to return superevent urls from /api/-->/apiweb/
# Note that event files are never exposed to the public and so aren't 
# subject to the same private api vs public apiweb caching schemes
def build_apiweb_uri(relative_uri, request=None):
    absolute_uri = build_absolute_uri(relative_uri, request=request)

    # Return the apiweb url for superevents:
    if '/superevents/' in absolute_uri:
        absolute_uri = absolute_uri.replace('/api/', '/apiweb/')

    return absolute_uri

gracedb/gwtc/urls.py
from django.conf.urls import url, include
from django.urls import path
from superevent.models import Superevent
from superevent import views

app_name = 'gwtc'


# URLs which are nested below a superevent detail
# These are included under a superevent's ID URL prefix (see below)
suburlpatterns = [

    # Superevent detail view
    url(r'^view/$', views.SupereventDetailView.as_view(), name="view"),

    # File list (file detail/download is handled through the API)
    url(r'^files/$', views.SupereventFileList.as_view(), name="file-list"),
]

# Legacy URL patterns - don't really need them, but we use them for the
# convenience of users who may be accustomed to the legacy event URL patterns

# public page url patterns. This needs to go first so django matches 
# the 'public' string before parsing it interprets it as a superevent_id.
# Note to future generations: don't name a GW 'public' or the link breaks.

public_urlpatterns = [
    # The /superevents/public/ url route gets redirected to the 
    # latest observation run.
    path('public/', views.public_alerts_redirect,
        name="public-alerts-redirect"),

    # each run has its own page, but must be in the list of runs that's 
    # in settings/base.py. Otherwise, 404 (this gets defined in the view). 
    # the "obsrun" variable controls which events are shown.
     path('public/<slug:obsrun>/', views.SupereventPublic.as_view(),
         name="public-alerts"),

]
legacy_urlpatterns = public_urlpatterns + [
    # Legacy URLs for superevent detail view
    path('<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview1"),
    path('view/<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview2"),
]

# Full urlpatterns: legacy urls plus suburlpatterns nested under
# superevent_id
urlpatterns = legacy_urlpatterns + [
    path('<str:superevent_id>/',
        include(suburlpatterns)),

]

gracedb/alerts/models.py
from collections import defaultdict
import logging
import random
import textwrap
import six

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.core.mail import EmailMessage
from django.db import models
from django.utils import timezone
from django.utils.http import urlencode

from django_twilio.client import twilio_client

from core.models import CleanSaveModel
from .fields import PhoneNumberField
from .phone import get_twilio_from


# Set up logger
logger = logging.getLogger(__name__)

# Set up user model
UserModel = get_user_model()

###############################################################################
# Contacts ####################################################################
###############################################################################
class Contact(CleanSaveModel):
    # Phone contact methods
    CONTACT_PHONE_CALL = 'C'
    CONTACT_PHONE_TEXT = 'T'
    CONTACT_PHONE_BOTH = 'B'
    CONTACT_PHONE_METHODS = (
        (CONTACT_PHONE_CALL, 'Call'),
        (CONTACT_PHONE_TEXT, 'Text'),
        (CONTACT_PHONE_BOTH, 'Call and text'),
    )
    # Number of digits in verification codes
    CODE_DIGITS = 6

    # Fields
    user = models.ForeignKey(UserModel, null=False, on_delete=models.CASCADE)
    description = models.CharField(max_length=30, blank=False, null=False)
    email = models.EmailField(blank=True, null=True)
    phone = PhoneNumberField(blank=True, max_length=255, null=True)
    phone_method = models.CharField(max_length=1, null=True, blank=True,
        choices=CONTACT_PHONE_METHODS, default=None)
    verified = models.BooleanField(default=False, editable=False)
    verification_code = models.IntegerField(null=True, editable=False)
    verification_expiration = models.DateTimeField(null=True, editable=False)
    # Fields for tracking when certain things happen
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    verified_time = models.DateTimeField(null=True, blank=True, editable=False)

    def __str__(self):
        return "{0}: {1}".format(self.user.username, self.description)

    def clean(self):
        # Mostly used for preventing creation of bad Contact
        # objects through the Django interface.
        super(Contact, self).clean()

        err_dict = defaultdict(list)
        # If a phone number is given, require either call or text to be True.
        if (self.phone is not None and self.phone_method is None):
            err_msg = 'Choose a phone contact method.'
            err_dict['phone_method'].append(err_msg)

        if (self.phone is None and self.phone_method is not None):
            err_msg = '"Call" and "text" should be False for non-phone alerts.'
            err_dict['phone'].append(err_msg)

        # Only one contact method is allowed
        if (self.email is not None and self.phone is not None):
            err_msg = \
                'Only one contact method (email or phone) can be selected.'
            err_dict[NON_FIELD_ERRORS].append(err_msg)

        # If no e-mail or phone given, raise error.
        # We have to skip this due to really annoying behavior with forms.. :(
        #if not (self.email or self.phone):
        #    err_msg = \
        #        'One contact method (email or phone) is required.'
        #    err_dict[NON_FIELD_ERRORS].append(err_msg)

        if err_dict:
            raise ValidationError(err_dict)

    def generate_verification_code(self):
        self.verification_code = random.randint(10**(self.CODE_DIGITS-1),
            (10**self.CODE_DIGITS)-1)
        self.verification_expiration = timezone.now() + \
            settings.VERIFICATION_CODE_LIFETIME
        self.save(update_fields=['verification_code',
            'verification_expiration'])

    def send_verification_code(self):
        # Message for texts and emails
        msg = ('Verification code for contact "{desc}" on {host}: {code}. '
            'If you did not request a verification code or do not know what '
            'this is, please disregard.').format(desc=self.description,
            host=settings.LIGO_FQDN, code=self.verification_code)

        if self.email:
            subject = 'Verification code for contact "{desc}" on {host}' \
                .format(desc=self.description, host=settings.LIGO_FQDN)
            email = EmailMessage(subject, msg,
                from_email=settings.ALERT_EMAIL_FROM, to=[self.email])
            email.send()
        elif self.phone:
            from_ = get_twilio_from()

            if (self.phone_method == self.CONTACT_PHONE_CALL):
                # If phone method is only call, send a call

                # Convert code to a string with spaces between the numbers
                # so it's pronounced properly by text-to-voice
                code = " ".join(str(self.verification_code))
                urlparams = urlencode({'code': code})
                twiml_url = '{base}{twiml_bin}?{params}'.format(
                    base=settings.TWIML_BASE_URL,
                    twiml_bin=settings.TWIML_BIN['verify'],
                    params=urlparams)
                twilio_client.calls.create(to=self.phone, from_=from_,
                    url=twiml_url, method='GET')
            else:
                # If method is text or both, send a text
                twilio_client.messages.create(to=self.phone, from_=from_,
                    body=msg)

    def verify(self):
        if not self.verified:
            self.verified = True
            self.verified_time = timezone.now()
            self.save(update_fields=['verified', 'verified_time'])

    def display(self):
        if self.email:
            return "Email {0}".format(self.email)
        elif self.phone:
            if self.phone_method == self.CONTACT_PHONE_BOTH:
                return "Call and text {0}".format(self.phone)
            elif self.phone_method == self.CONTACT_PHONE_CALL:
                return "Call {0}".format(self.phone)
            if self.phone_method == self.CONTACT_PHONE_TEXT:
                return "Text {0}".format(self.phone)

    def print_info(self):
        """Prints information about Contact object; useful for debugging."""
        info_str = textwrap.dedent("""\
            Contact "{description}" (user {username})
            E-mail: {email}
            Phone: {phone} (method={method})
            Created: {created_time}
            Last updated: {updated_time}
            Verified: {verified} ({verified_time})
        """).format(description=self.description, username=self.user.username,
        email=self.email, phone=self.phone, method=self.phone_method,
        created_time=self.created, updated_time=self.updated,
        verified=self.verified, verified_time=self.verified_time)
        print(info_str)


###############################################################################
# Notifications ###############################################################
###############################################################################
class Notification(models.Model):
    # Notification categories
    NOTIFICATION_CATEGORY_EVENT = 'E'
    NOTIFICATION_CATEGORY_SUPEREVENT = 'S'
    NOTIFICATION_CATEGORY_CHOICES = (
        (NOTIFICATION_CATEGORY_EVENT, 'Event'),
        (NOTIFICATION_CATEGORY_SUPEREVENT, 'Superevent'),
    )
    user = models.ForeignKey(UserModel, null=False, on_delete=models.CASCADE)
    contacts = models.ManyToManyField(Contact)
    description = models.CharField(max_length=40, blank=False, null=False)
    far_threshold = models.FloatField(blank=True, null=True)
    labels = models.ManyToManyField('events.label', blank=True)
    label_query = models.CharField(max_length=100, null=True, blank=True)
    category = models.CharField(max_length=1, null=False, blank=False,
        choices=NOTIFICATION_CATEGORY_CHOICES,
        default=NOTIFICATION_CATEGORY_SUPEREVENT)
    # Fields for tracking when certain things happen
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # Whether the event possibly has a neutron star in it.
    # The logic for determining this is defined in a method below.
    ns_candidate = models.BooleanField(default=False)
    # Event-only fields
    groups = models.ManyToManyField('events.group', blank=True)
    pipelines = models.ManyToManyField('events.pipeline', blank=True)
    searches = models.ManyToManyField('events.search', blank=True)

    def __str__(self):
        return six.text_type(
            "{username}: {display}".format(
                username=self.user.username,
                display=self.display()
            )
        )

    def display(self):
        kwargs = {}
        if self.category == self.NOTIFICATION_CATEGORY_EVENT:
            output = 'Event'
        elif self.category == self.NOTIFICATION_CATEGORY_SUPEREVENT:
            output = 'Superevent'

        # Add label stuff
        if self.label_query or self.labels.exists():
            action = 'labeled with {labels}'
            if self.label_query:
                labels = '({0})'.format(self.label_query)
            else:
                labels = " & ".join([l.name for l in self.labels.all()])
                if self.labels.count() > 1:
                    labels = '({0})'.format(labels)
            action = action.format(labels=labels)
        else:
            if self.far_threshold or self.ns_candidate:
                action = 'created or updated'
            else:
                action = 'created'
        output += ' {action}'.format(action=action)

        # Add groups, pipelines, searches for event-type notifications
        if self.category == self.NOTIFICATION_CATEGORY_EVENT:
            output += ' & {groups} & {pipelines} & {searches}'
            if self.groups.exists():
                grps = " | ".join([g.name for g in self.groups.all()])

gracedb/superevents/forms.py
import logging
import os

from django import forms

from superevents.models import Signoff

# Set up logger
logger = logging.getLogger(__name__)


class SignoffForm(forms.ModelForm):

    class Meta:
        model = Signoff
        fields = ['status', 'comment', 'signoff_type', 'instrument']

    def __init__(self, *args, **kwargs):
        super(SignoffForm, self).__init__(*args, **kwargs)
        # Hide some fields that we will populate either by default
        # when we instantiate the form or with the request data
        self.fields['signoff_type'].widget = forms.HiddenInput()
        self.fields['instrument'].widget = forms.HiddenInput()

gracedb/api/v2/events/views.py
from ...v1.events.views import *

gracedb/api/v2/main/views.py
from ...v1.main.views import *

gracedb/api/v2/superevents/views.py
from ...v1.superevents.views import *

gracedb/templates/superevents/advocate_signoff_frag.html
<div class="signoff-area">

  <!-- Adding confirmation dialog support -->
  {% load confirmation_text %}
  <script>
    function advClickConfirm(message) {
      return confirm(message);
    }
  </script>

  <table class="table-condensed table-resp-gracedb shadow p-3 mb-5 rounded">
    <thead>
      <tr><th><h3>Advocate Signoff</h3></th></tr>
    </thead>
    <tr>
      <td>
        <p>You are seeing this section because you're a designated EM followup advocate.
        {% if advocate_signoff_exists %}
        This event has already been signed off on. Use the form below if you wish to edit or delete the record.
        {% else %}
        This event still requires EM Followup advocate signoff.
        {% endif %}
        </p>

        <form class="signoff_form">
          <table align="center">
            {{ advocate_signoff_form.as_table }}
            <tr>
              <td></td>
              <td>
                {# inputs are disabled here, enabled by jquery code on page load. Otherwise users who click quickly can activate the form before the jquery is fully loaded #}
                {% if advocate_signoff_exists %}
                {% with advocate_signoff_type|add:advocate_signoff_instrument as typeinst %}
                {% with signoff_confirm_text="update_advocate_signoff,"|add:superevent.superevent_id|confirmation_text %}
                <input type="submit"
                       formaction="{% url "legacy_apiweb:default:superevents:superevent-signoff-detail" superevent.superevent_id typeinst %}"
                       value="Update signoff"
                       class="btn btn-warning"
                       id="update" disabled
                       onclick="return advClickConfirm('{{signoff_confirm_text}}')">
                {% endwith %}
                {% with signoff_confirm_text="delete_advocate_signoff,"|add:superevent.superevent_id|confirmation_text %}
                <input type="submit"
                       formaction="{% url "legacy_apiweb:default:superevents:superevent-signoff-detail" superevent.superevent_id typeinst %}"
                       value="Delete signoff"
                       class="btn btn-danger"
                       id="delete" disabled
                       onclick="return advClickConfirm('{{signoff_confirm_text}}')">
                {% endwith %}
                {% endwith %}
                {% else %}
                {% with signoff_confirm_text="create_advocate_signoff,"|add:superevent.superevent_id|confirmation_text %} 
                <input type="submit"
                       value="Create signoff"
                       class="btn btn-success"
                       formaction={% url "legacy_apiweb:default:superevents:superevent-signoff-list" superevent.superevent_id %}
                       disabled
                       onclick="return advClickConfirm('{{signoff_confirm_text}}')">
                {% endwith %}
                {% endif %}
              </td>
            </tr>
          </table>
        </form>
      </td></tr></table>
</div>

gracedb/templates/superevents/emo_form_frag.html
<div class="row pt-3 justify-content-center">
<div class="col">

<p><center>
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#EMOform" aria-expanded="false" aria-controls="EMOform">
    Expand/Collapse EM Observation Report
</button>
</center></p>
<div class="collapse" id="EMOform">      

    <div data-dojo-type="dijit/form/Form" id="emoFormContainer"
        data-dojo-id="emoFormContainer" encType="multipart/form-data" action=""
        method="">
        <script>
         require(["dojo/parser", "dijit/form/Form", "dijit/form/Button", "dijit/form/ValidationTextBox", "dijit/form/DateTextBox"]);
         </script>
        		 
        <script type="dojo/on" data-dojo-event="reset">
        return confirm('Press OK to reset widget values');
        </script>
        <script type="dojo/on" data-dojo-event="submit">
        if(this.validate()){
        return confirm('Form is valid, press OK to submit');
        }else{
        alert('Form contains invalid data.  Please correct first');
        return false;
        }
        return true;
        </script>
        
        <form method="POST" id="emo_submit_form">
        <table>
        
        <tr><td><a href=# onclick="alert('Group with which the LSC has signed a trust agreement, hereby providing data 
        under its trust (required).'); return false;">
        Which MOU Group provides this report?</a></td>       <td><select name="group">
        <option value=""></option>
        {% for g in emgroups %}
        <option value="{{ g }}">{{ g }}</option>
        {% endfor %} </select> </td> </tr>
        
        <tr><td><a href=# onclick="alert('RA and Dec specify a center point of a rectangle that is aligned equatorially. Or list of centers. They must be in decimal degrees 0<=RA<=360 -90<=Dec<=90, in the J2000 frame.');return false;">
        RA (decimal degrees)</a></td>             <td><input type="text" name="ra_list" value="" size=80/></td></tr>
        
        <tr><td><a href=# onclick="alert('RA and Dec specify a center point of a rectangle that is aligned equatorially. Or list of centers. They must be in decimal degrees 0<=RA<=360 -90<=Dec<=90, in the J2000 frame.');return false;">
        Dec (decimal degrees)</a></td>            <td><input type="text" name="dec_list" value="" size=80/></td></tr>
        
        <tr><td><a href=# onclick="alert('RAWidth and DecWidth specify the size of a a rectangle that is aligned equatorially. Thus the edge of the box is distant from the center by half of the width.');return false;">
        RAwidth (decimal degrees)</a></td>        <td><input type="text" name="ra_width_list" value=""/></td></tr>
        
        <tr><td><a href=# onclick="alert('RAWidth and DecWidth specify the size of a a rectangle that is aligned equatorially. Thus the edge of the box is distant from the center by half of the width.');return false;">
        Decwidth (decimal degrees)</a></td>       <td><input type="text" name="dec_width_list" value=""/></td></tr>
        
        <tr><td><a href=# onclick="alert('The time at the beginning of a time interval during which the observation was taken. Or list of times. UTC in ISO 8601 format.');return false;">
        StartTime</a></td>
        <td><input type="text" name="start_time_list" value="" size=80/></td>
        </tr>
        
        <tr><td><a href=# onclick="alert('This is the on-source exposure time in seconds (or the duration of the observation).');return false;">
        On source exposure (seconds)</a></td>       <td><input type="text" name="duration_list" value=""/></td></tr>
        
        <tr><td><a href=# onclick="alert('A natural language report.');return false;">
        Report as text</a></td>         <td colspan=2><textarea name="comment" rows="8" cols="50"></textarea></td></tr>
        
        </table>
        <input type="submit" value="Submit EMBB Observation Report"/>
        </form>
        
        </div>
</div>

</div>
</div>

gracedb/templates/superevents/executive_signoff_frag.html
<table class="table-condensed table-resp-gracedb shadow p-3 mb-5 rounded">
                    <thead>
                        <tr><th><h3>Executive Actions</h3></th></tr>
                    </thead>
                    <tr><td>
                <center>
                    <b>Note:</b> this action is irreversible without manual intervention by an admin.
                    <br>
                    <br>
                    <form action="{% url "legacy_apiweb:default:superevents:superevent-confirm-as-gw" superevent.superevent_id %}" method="POST" id="confirm_as_gw_form">
                        <input type="submit" value="Confirm this superevent as a GW" class="btn btn-danger permButtonClass" disabled>
                    </form>
                </center>
                        </td></tr>
</table>

gracedb/templates/superevents/log_create_form.html
<h2>Create log message</h2>

<div style="padding-bottom: 20px">
<form enctype="multipart/form-data" action="{% url "superevents:create-log" superevent.superevent_id %}" method="POST">
    <table>
        {{ log_create_form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
</div>

gracedb/templates/superevents/superevent_info_table.html
{% load timeutil %}
{% load scientific %}
{% load mediaviews %}

<br>
<br>

    <table class="table-hover table-condensed table-resp-gracedb shadow p-3 mb-5 rounded">
      <!-- Table Header -->
      <thead>
      <tr>
        <th colspan="2"><h3>Superevent Information</h3></th>
      </tr>
      </thead>

      <!-- Begin Table Data -->
      <tbody>
      <tr>
        <td> Superevent ID </td>
        <td> {{ superevent.default_superevent_id }} </td>
      </tr>

      {% if superevent.is_gw %}
      <tr>
        <td> GW ID </td>
        <td> {{ superevent.gw_id }} </td>
      </tr>
      {% endif %}

      <tr>
        <td> Category </td>
        <td> {{ superevent.get_category_display }} </td>
      </tr>

      <tr>
        <td> Labels </td>
        <td>
        {% for labelling in superevent.labelling_set.all %}
                    <span style="color: {{labelling.label.defaultColor}};" class="label"
                       data-toggle="tooltip"
                       data-placement="top"
                       data-html="true"
                       title="<em>{{labelling.label.description}}</em><br>
                      <b>Added by:</b> {{labelling.creator.get_full_name}}<br>
                      <b>Added:</b> {{labelling.created}}">
               {{ labelling.label.name }}</span>
       {% endfor %}
        </td>
      </tr>

      <tr>
        <td> Event </td>
        <td>
            {{ preferred_event | event_link_filter }}
        </td>
      </tr>

      <tr>
        <td> GW events </td>
        <td>
            <div>
            {% for ev in internal_events %}
              {{ ev | event_link_filter }}
            {% endfor %}
            </div>
        </td>
      </tr>

      <tr>
        <td> External events </td>
        <td>
            <div>
            {% if external_events %}
            {% for graceid in external_events %}
            <a href="{% url "view" graceid %}">{{ graceid }}</a>
            {% endfor %}
            {% else %}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% endif %}
            </div>

        </td>
      </tr>

      <tr>
        <td> t<sub>start</sub> (GPS time)</td>
        <td> {{ superevent.t_start|floatformat:2 }} </td>
      </tr>

      <tr>
        <td> t<sub>0</sub> (GPS time)</td>
        <td> {{ superevent.t_0|floatformat:2 }} </td>
      </tr>

      <tr>
        <td> t<sub>end</sub> (GPS time)</td>
        <td> {{ superevent.t_end|floatformat:2 }} </td>
      </tr>

      <tr>
        <td> {{ "submitted"|timeselect:"utc" }} </td>
        <td> {{ superevent.created|multiTime:"submitted" }} </td>
      </tr>

      <tr>
        <td> Links </td>
        <td> <a href="{% url "superevents:file-list" superevent.superevent_id %}">Data</a> </td>
      </tr>
      </tbody>

    </table> 
    

gracedb/templates/superevents/superevent_info_table_public.html
{% load timeutil %}
{% load scientific %}
<br>
<br>

    <table class="table-hover table-condensed table-resp-gracedb shadow p-3 mb-5 rounded">
      <!-- Table Header -->
      <thead>
      <tr>
        <th colspan="2"><h3>Superevent Information</h3></th>
      </tr>
      </thead>

      <!-- Begin Table Data -->
      <tbody>
      <tr>
        <td> Superevent ID </td>
        <td> {{ superevent.default_superevent_id }} </td>
      </tr>

      {% if superevent.is_gw %}
      <tr>
        <td> GW ID </td>
        <td> {{ superevent.gw_id }} </td>
      </tr>
      {% endif %}

      <tr>
        <td> Category </td>
        <td> {{ superevent.get_category_display }} </td>
      </tr>

      <tr>
        <td> FAR (Hz) </td>
        <td> {% if far_is_upper_limit %} &lt; {% endif %}{{ display_far|scientific }} </td>
      </tr>

      <tr>
        <td> FAR (yr<sup>-1</sup>)  </td>
        <td> {% if far_is_upper_limit %} &lt; {% endif %}{{ display_far_hr }} </td>
      </tr>

      <tr>
        <td> t<sub>0</sub> (GPS time)</td>
        <td> {{ superevent.t_0|floatformat:2 }} </td>
      </tr>

      <tr>
        <td> t<sub>end</sub> (GPS time)</td>
        <td> {{ superevent.t_end|floatformat:2 }} </td>
      </tr>

      <tr>
        <td> {{ "submitted"|timeselect:"utc" }} </td>
        <td> {{ superevent.created|multiTime:"submitted" }} </td>
      </tr>

      <tr>
        <td> Links </td>
        <td> <a href="{% url "superevents:file-list" superevent.superevent_id %}">Data</a> </td>
      </tr>
      </tbody>

    </table>