config/urls.py
from django.conf import settings

from django.urls import re_path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

# Import feeds
import core.views
from events.feeds import EventFeed, feedview
import events.reports
import events.views
from ligoauth.views import (
    manage_password, ShibLoginView, ShibPostLoginView
)
import search.views

# Django admin auto-discover
admin.autodiscover()

feeds = {
    'latest' : EventFeed
}


urlpatterns = [
    re_path(r'^$', events.views.index, name="home"),
    re_path(r'^navbar_only$', TemplateView.as_view(
        template_name='navbar_only.html'), name="navbar-only"),
    re_path(r'^SPInfo', TemplateView.as_view(template_name='gracedb/spinfo.html'),
         name="spinfo"),
    re_path(r'^SPPrivacy', TemplateView.as_view(
        template_name='gracedb/spprivacy.html'), name="spprivacy"),
    re_path(r'^DiscoveryService', TemplateView.as_view(
        template_name='discovery.html'), name="discovery"),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^superevents/', include('superevents.urls')),
    re_path(r'^alerts/', include('alerts.urls')),
    re_path(r'^feeds/(?P<url>.*)/$', EventFeed()),
    re_path(r'^feeds/$', feedview, name="feeds"),

    re_path(r'^other/$', TemplateView.as_view(template_name='other.html'),
        name='other'),
    re_path(r'^performance/$', events.views.performance, name="performance"),
    re_path(r'^reports/$', events.reports.reports_page_context, name="reports"),
    re_path(r'^latest/$', search.views.latest, name="latest"),
    #(r'^reports/(?P<path>.+)$', 'django.views.static.serve',
    #        {'document_root': settings.LATENCY_REPORT_DEST_DIR}),
    re_path(r'^search/$', search.views.search, name="mainsearch"),

    # Authentication
    re_path(r'^login/$', ShibLoginView.as_view(), name='login'),
    re_path(r'^post-login/$', ShibPostLoginView.as_view(), name='post-login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Password management
    re_path('^manage-password/$', manage_password, name='manage-password'),

    # API URLs
    re_path(r'^api/', include('api.urls')),
    # Legacy API URLs - must be maintained!
    re_path(r'^apibasic/', include('api.urls', namespace='legacy_apibasic')),
    re_path(r'^apiweb/', include('api.urls', namespace='legacy_apiweb')),

    # Heartbeat URL
    re_path(r'^heartbeat/$', core.views.heartbeat, name='heartbeat'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),

    # Sessions
    re_path(r'^', include('user_sessions.urls', 'user_sessions')),

]

# We don't require settings.DEBUG for django-silk since running unit tests
# by default setings settings.DEBUG to False, unless you use the
# --debug-mode flag
if ('silk' in settings.INSTALLED_APPS):
    # Add django-silk
    urlpatterns = [
        re_path(r'^silk/', include('silk.urls', namespace='silk'))
    ] + urlpatterns

# Add django-debug-toolbar
if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

gracedb/alerts/urls.py
from django.urls import re_path

from . import views

app_name = 'alerts'


urlpatterns = [
    # Base /options/ URL
    re_path(r'^$', views.index, name="index"),

    # Contacts
    re_path(r'^contact/create/', views.CreateContactView.as_view(),
        name='create-contact'),
    re_path(r'^contact/(?P<pk>\d+)/edit/$', views.EditContactView.as_view(),
        name="edit-contact"),
    re_path(r'^contact/(?P<pk>\d+)/delete/$', views.DeleteContactView.as_view(),
        name="delete-contact"),
    re_path(r'^contact/(?P<pk>\d+)/test/$', views.TestContactView.as_view(),
        name="test-contact"),
    re_path(r'^contact/(?P<pk>\d+)/request-code/$',
        views.RequestVerificationCodeView.as_view(),
        name="request-verification-code"),
    re_path(r'^contact/(?P<pk>\d+)/verify/$', views.VerifyContactView.as_view(),
        name="verify-contact"),

    # Notifications
    re_path(r'^notification/create/$', views.CreateNotificationView.as_view(),
        name="create-notification"),
    re_path(r'^notification/(?P<pk>\d+)/edit/$',
        views.EditNotificationView.as_view(), name="edit-notification"),
    re_path(r'^notification/(?P<pk>\d+)/delete/$',
        views.DeleteNotificationView.as_view(), name="delete-notification"),
]

gracedb/api/urls.py
from django.urls import re_path, include

from .v1 import urls as v1_urls
from .v2 import urls as v2_urls

app_name = 'api'

urlpatterns = [
    re_path(r'^', include((v1_urls, 'default'))),
    re_path(r'^v1/', include((v1_urls, 'v1'))),
    re_path(r'^v2/', include((v2_urls, 'v2'))),
]

gracedb/core/urls.py
# URL utilities

from django.contrib.sites.models import Site


def build_absolute_uri(relative_uri, request=None):
    if request is not None:
        return request.build_absolute_uri(relative_uri)
    else:
        # Assume HTTPS
        domain = Site.objects.get_current().domain
        return 'https://' + domain + relative_uri

# A helper function to return superevent urls from /api/-->/apiweb/
# Note that event files are never exposed to the public and so aren't 
# subject to the same private api vs public apiweb caching schemes
def build_apiweb_uri(relative_uri, request=None):
    absolute_uri = build_absolute_uri(relative_uri, request=request)

    # Return the apiweb url for superevents:
    if '/superevents/' in absolute_uri:
        absolute_uri = absolute_uri.replace('/api/', '/apiweb/')

    return absolute_uri

gracedb/gwtc/urls.py
from django.conf.urls import url, include
from django.urls import path
from superevent.models import Superevent
from superevent import views

app_name = 'gwtc'


# URLs which are nested below a superevent detail
# These are included under a superevent's ID URL prefix (see below)
suburlpatterns = [

    # Superevent detail view
    url(r'^view/$', views.SupereventDetailView.as_view(), name="view"),

    # File list (file detail/download is handled through the API)
    url(r'^files/$', views.SupereventFileList.as_view(), name="file-list"),
]

# Legacy URL patterns - don't really need them, but we use them for the
# convenience of users who may be accustomed to the legacy event URL patterns

# public page url patterns. This needs to go first so django matches 
# the 'public' string before parsing it interprets it as a superevent_id.
# Note to future generations: don't name a GW 'public' or the link breaks.

public_urlpatterns = [
    # The /superevents/public/ url route gets redirected to the 
    # latest observation run.
    path('public/', views.public_alerts_redirect,
        name="public-alerts-redirect"),

    # each run has its own page, but must be in the list of runs that's 
    # in settings/base.py. Otherwise, 404 (this gets defined in the view). 
    # the "obsrun" variable controls which events are shown.
     path('public/<slug:obsrun>/', views.SupereventPublic.as_view(),
         name="public-alerts"),

]
legacy_urlpatterns = public_urlpatterns + [
    # Legacy URLs for superevent detail view
    path('<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview1"),
    path('view/<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview2"),
]

# Full urlpatterns: legacy urls plus suburlpatterns nested under
# superevent_id
urlpatterns = legacy_urlpatterns + [
    path('<str:superevent_id>/',
        include(suburlpatterns)),

]

gracedb/superevents/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from .models import Superevent
from . import views

app_name = 'superevents'


# URLs which are nested below a superevent detail
# These are included under a superevent's ID URL prefix (see below)
suburlpatterns = [

    # Superevent detail view
    re_path(r'^view/$', views.SupereventDetailView.as_view(), name="view"),

    # File list (file detail/download is handled through the API)
    re_path(r'^files/$', views.SupereventFileList.as_view(), name="file-list"),
]

# Legacy URL patterns - don't really need them, but we use them for the
# convenience of users who may be accustomed to the legacy event URL patterns

# public page url patterns. This needs to go first so django matches 
# the 'public' string before parsing it interprets it as a superevent_id.
# Note to future generations: don't name a GW 'public' or the link breaks.

public_urlpatterns = [
    # The /superevents/public/ url route gets redirected to the 
    # latest observation run.
    path('public/', views.public_alerts_redirect,
        name="public-alerts-redirect"),

    # each run has its own page, but must be in the list of runs that's 
    # in settings/base.py. Otherwise, 404 (this gets defined in the view). 
    # the "obsrun" variable controls which events are shown.
     path('public/<slug:obsrun>/', views.SupereventPublic.as_view(),
         name="public-alerts"),

]
legacy_urlpatterns = public_urlpatterns + [
    # Legacy URLs for superevent detail view
    path('<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview1"),
    path('view/<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview2"),
]

# Full urlpatterns: legacy urls plus suburlpatterns nested under
# superevent_id
urlpatterns = legacy_urlpatterns + [
    path('<str:superevent_id>/',
        include(suburlpatterns)),

]

gracedb/core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class ModelFormUpdateMixin(forms.ModelForm):
    """
    ModelForm mixin which provides the capability to update an existing model
    object with input data which is incomplete - i.e., doesn't contain all
    fields required by the form.

    Usage:
        # For a model with attributes 'attr1' and 'attr2 and a form that
        # normally requires both attributes
        data_dict = {'attr1': 'example'}
        ExampleForm(data_dict, instance=model_instance)
    """

    def __init__(self, *args, **kwargs):
        super(ModelFormUpdateMixin, self).__init__(*args, **kwargs)

        # If instance is provided, populate missing data
        if self.instance.pk is not None:
            self.populate_missing_data()

    def get_instance_data(self):
        # Should be overridden by concrete derived classes
        return NotImplemented

    def populate_missing_data(self):
        """
        Populate missing data fields from model instance.

        NOTE: the actual data dictionary is populated, not initial data,
        because missing fields in the input data would still be ignored.
        """
        if self.instance.pk is None:
            self.add_error(None, _('Model instance not found'))

        # Insert instance data for missing fields only
        instance_data = self.get_instance_data()
        for key in self.fields:
            if not key in self.data and instance_data[key]:
                self.data[key] = instance_data[key]


class MultipleForm(forms.Form):
    key = None
    key_field = forms.CharField(max_length=30, widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(MultipleForm, self).__init__(*args, **kwargs)
        self.fields['key_field'].initial = self.key

gracedb/events/forms.py
import logging

from django import forms
from django.utils.safestring import mark_safe
from django.utils.html import escape
from .models import Event, Group, Label, GrbEvent
from .models import Pipeline, Search, Signoff
from django.contrib.auth.models import User
from django.core.exceptions import FieldError
from django.forms import ModelForm

from pyparsing import ParseException

# Set up logger
logger = logging.getLogger(__name__)


class CreateEventForm(forms.Form):
    eventFile = forms.FileField()
    group = forms.ModelChoiceField(queryset=Group.objects.all(), to_field_name='name')
    pipeline = forms.ModelChoiceField(queryset=Pipeline.objects.all(), to_field_name='name')
    search = forms.ModelChoiceField(queryset=Search.objects.all(), to_field_name='name',
        required=False)
    # List of labels as a comma-separated string
    labels = forms.ModelMultipleChoiceField(queryset=Label.objects.all(),
        required=False, to_field_name='name')

    # Offline boolean. required=False means that if the user
    # doesn't provide a value, we use the default defined in models.py.
    # This ensures backwards-compatibility for client versions which
    # don't specify this parameter.
    offline = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super(CreateEventForm, self).clean()

        # Don't allow protected labels
        labels = cleaned_data.get('labels')
        protected_labels = labels.filter(protected=True)
        if protected_labels.exists():
            raise forms.ValidationError({'labels': 'The following label(s) are'
                ' managed automatically and cannot be manually applied: {0}'
                .format(', '.join([l.name for l in protected_labels]))})

        return cleaned_data


class SignoffForm(ModelForm):
    class Meta:
        model = Signoff
        fields = [ 'status', 'comment' ] 


class GrbEventUpdateForm(ModelForm):
    class Meta:
        model = GrbEvent
        fields = ['ra', 'dec', 'error_radius', 't90', 'redshift',
                  'designation']

gracedb/superevents/forms.py
import logging
import os

from django import forms

from superevents.models import Signoff

# Set up logger
logger = logging.getLogger(__name__)


class SignoffForm(forms.ModelForm):

    class Meta:
        model = Signoff
        fields = ['status', 'comment', 'signoff_type', 'instrument']

    def __init__(self, *args, **kwargs):
        super(SignoffForm, self).__init__(*args, **kwargs)
        # Hide some fields that we will populate either by default
        # when we instantiate the form or with the request data
        self.fields['signoff_type'].widget = forms.HiddenInput()
        self.fields['instrument'].widget = forms.HiddenInput()

gracedb/api/v2/events/views.py
from ...v1.events.views import *

gracedb/api/v2/main/views.py
from ...v1.main.views import *

gracedb/api/v2/superevents/views.py
from ...v1.superevents.views import *

gracedb/core/views.py
import logging

from django.http import HttpResponse
from django.views.generic.edit import FormView

from .decorators import ignore_maintenance_mode

# Set up logger
logger = logging.getLogger(__name__)


@ignore_maintenance_mode
def heartbeat(request):
    # Do something (?) and return 200 response
    return HttpResponse()


class MultipleFormView(FormView):
    """Requires forms to inherit from core.forms.MultipleForm"""
    form_classes = []

    @property
    def form_classes(self):
        if not hasattr(self, '_form_classes'):
            self._form_classes = {f.key: f for f in self.form_class_list}
        return self._form_classes

    def get_forms(self, form_classes=None):
        if (form_classes is None):
            form_classes = self.form_classes
        return [form(**self.get_form_kwargs(form.key)) for form in
            form_classes]

    def get_form_kwargs(self, form_key):
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
        }
        if (self.request.method in ('POST', 'PUT')):
            key_field = self.request.POST.get('key_field', None)
            if (key_field is not None and key_field == form_key):
                kwargs.update({'data': self.request.POST,
                    'files': self.request.FILES})
        return kwargs

    def get(self, request, *args, **kwargs):
        forms = self.get_forms()
        return self.render_to_response(self.get_context_data(forms=forms))

    def post(self, request, *args, **kwargs):
        form_key = request.POST.get('key_field')
        forms = self.get_forms()
        return self._process_individual_form(form_key, forms)

    def forms_valid(self, form):
        form_valid_method = '{key}_form_valid'.format(key=form.key)
        if hasattr(self, form_valid_method):
            return getattr(self, form_valid_method)(form)
        else:
            return HttpResponseRedirect(self.success_url)

    def forms_invalid(self, forms):
        return self.render_to_response(self.get_context_data(forms=forms))

    def _get_form_by_key(self, key, forms):
        form_keys = [f.key for f in forms]
        return forms[form_keys.index(key)]

    def _process_individual_form(self, form_key, forms):
        form = self._get_form_by_key(form_key, forms)
        if form.is_valid():
            return self.forms_valid(form)
        else:
            return self.forms_invalid(forms)

gracedb/templates/503.html
{% extends "base.html" %}

{% block title %}503 &ndash; Service Unavailable{{ object.graceid }}{% endblock %}
{% block heading %}Not Found {{ object.graceid }}{% endblock %}

{% block content %}
    <p>GraceDB is temporarily unavailable.  Please check back later.</p>
    {{ message|safe }}
{% endblock %}

gracedb/templates/discovery.html
{% extends "base.html" %}

{% block title %}Log-In{% endblock %}
{% block heading %}<h5>Please choose how to log in</h5><hr> {% endblock %}
{% block pageid %}Discovery Service{% endblock %}

{% block jscript %}
<link rel="stylesheet" type="text/css" href="/shibboleth-ds/idpselect.css" />
{% endblock %}

{% block content %}
<div class="d-flex p-2 flex-column justify-content-center">
<div id="idpSelect"> 
</div> 

<div>
    <script src="/shibboleth-ds/idpselect_config.js" type="text/javascript" language="javascript"></script>
    <script src="/shibboleth-ds/idpselect.js" type="text/javascript" language="javascript"></script>
</div>

<br>

<div id="consent" style="width:389px; padding:15px">
    <p>This site uses cookies to manage sessions, but not track activity across
    other sites or services.</p>

    <p>Identifying information is obtained from the Identity Provider and your
    IP address. These data are used to record annotations to GraceDB and its
    associated data products. Log files are stored and used in security audits and problem
    resolution.</p>

    <p>By proceeding, you are consenting to the use of cookies for this session.</p>
</div>
</div>

{% endblock %}

gracedb/templates/forbidden.html
{% extends "base.html" %}

{% block title %}403 &ndash; Forbidden{{ object.graceid }}{% endblock %}
{% block heading %}Forbidden{{ object.graceid }}{% endblock %}

{% block content %}
    <!-- <p>You are {{ error }} and the item you requested is not for you.</p> {{ message|safe }} -->
    <p>You are {{ user.username }} and the item you requested is not for you.</p> {{ error|safe }}
{% endblock %}

gracedb/templates/maintenance.html
{% extends "base.html" %}

{% block title %}Maintenance{% endblock %}
{% block heading %}{% endblock %}

{% block headcontents %}
{{ block.super }}
<style>
.maintenance-message {
    background-color: red;
    color: white;
    text-align: center;
    display: inline-block;
    border-radius: 5px;
    padding: 10px;
    min-width: 400px;
    max-width: 600px;
    box-shadow: 0 0 20px rgba(0,0,0,.2);
}
.maintenance-message p {
    font-weight: bold;
    font-size: 2rem;
    margin: 0;
}
</style>
{% endblock %}

{% block content %}

<div align="center" style="padding: 30px;">
    <div class="maintenance-message">
        <p>{{ message | safe }}</p>
    </div>
</div>

{% endblock %}

gracedb/templates/navbar_frag.html
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script>
$( document ).ready( function () {
    $( '.navbar a.dropdown-toggle' ).on( 'click', function ( e ) {
        var $el = $( this );
        var $parent = $( this ).offsetParent( ".dropdown-menu" );
        $( this ).parent( "li" ).toggleClass( 'show' );

        if ( !$parent.parent().hasClass( 'navbar-nav' ) ) {
            $el.next().css( { "top": $el[0].offsetTop, "left": $parent.outerWidth() - 4 } );
        }
        $( '.navbar-nav li.show' ).not( $( this ).parents( "li" ) ).removeClass( "show" );
        return false;
    } );
} );

</script>

<div class="fixed-top" style="margin-top: -75px; padding-top: 75px; box-shadow: 0 0 0.2rem rgba(0,0,0,.1), 0 0.2rem 0.4rem rgba(0,0,0,.2);">
  <nav class="navbar navbar-expand-md navbar-gracedb navbar-dark">
    <a class="navbar-brand text-white" href="/">
      <img src="{% static "images/logo.svg" %}" style="width:30px;">
      GraceDB  
      {% if config_name %}
      <span class="text-danger">({{ config_name }})</span>
      {% endif %}
    </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapsibleNavbar">

    <ul class="navbar-nav">
      <li class="nav-item">
      <div class="btn-group">
        <a class="btn btn-small btn-navbar shadow-none" href="{% url "superevents:public-alerts-redirect" %}" role="button">Public Alerts</a>
  <button type="button" class="btn btn-small shadow-none btn-split dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li> <div class="dropdown-item dropdown-toggle"><a href="{% url "superevents:public-alerts" "O4" %}" style="color: black; text-decoration: none;">O4</a></div>
    <ul class="dropdown-menu dropdown-submenu">
      <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "O4c" %}">O4c</a> </li>
      <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "O4b" %}">O4b</a> </li>
      <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "O4a" %}">O4a</a> </li>
    </ul></li>
    <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "ER16"%}">ER16</a> </li>
    <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "ER15"%}">ER15</a> </li>
    <li> <a class="dropdown-item" href="{% url "superevents:public-alerts" "O3" %}">O3</a> </li>
  </ul>
</div>
      </li>

      <li class="nav-item">
         <a class="nav-link text-light font-weight-light" href="{% url "latest" %}">Latest</a>
      </li>

      <li class="nav-item">
         <a class="nav-link text-light font-weight-light" href="{% url "mainsearch" %}">Search</a>
      </li>

      {% if user_is_internal %}

        <li class="nav-item">
           <a class="nav-link text-light font-weight-light" href="{% url "alerts:index" %}">Notifications</a>
        </li>

        <li class="nav-item">
           <a class="nav-link text-light font-weight-light" href="{% url "manage-pipelines" %}">Pipelines</a>
        </li>

      {% elif user_is_lvem %}
        <li class="nav-item">
           <a class="nav-link text-light font-weight-light" href="{% url "manage-password" %}">Manage Password</a>
        </li>

      {% endif %}

      <li class="nav-item">
         <a class="nav-link text-light font-weight-light" href="{% url "home" %}documentation/" target="_blank">Documentation</a>
      </li>

      {% if user %}
          {% if user.is_superuser %}
              <li class="nav-item">
                 <a class="nav-link text-light font-weight-light" href="{% url "home" %}admin_docs/" target="_blank">Admin Docs</a>
              </li>
          {% endif %}
      {% endif %}

      {% if user.is_authenticated %}

         <li class="nav-item">
            <a class="nav-link text-light font-weight-light" href="{% url "logout" %}?next={{ request.path }}">Logout</a>
         </li>

      {% else %}
         <li class="nav-item">
            <a class="nav-link text-light font-weight-light" href="{% url "login" %}?next={{ request.path }}">Login</a>
         </li>
      {% endif %}
    </ul>
  </div>
  </nav>

  <div class="container-fluid navbar-gracedb text-left">
           <span class="text-light" style="font-size:8pt">  
           {% if user.is_authenticated %}
           Authenticated as:
           {% if user.first_name %}
               {{ user.get_full_name }}
           {% else %}
               {{ user.username }}
           {% endif %}
           {% else %}
           Please log in to view full database contents.
           </span>
         {% endif %}
  </div>
</div>

gracedb/templates/navbar_only.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
{% load static %}
{% block headcontents %}
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
{% endblock %}
</head>
<div id="content">

<center>
<h1 class="docnav"> GraceDB &mdash; Gravitational-Wave Candidate Event Database</h1>
</center>

{% block nav %}
    {% include "navbar_frag.html" %}
{% endblock %}

        <p>&nbsp;</p> <!-- bad way to create vertical space -->

</div>

</body>
</html>

gracedb/templates/other.html
{% extends "base.html" %}

{% block title %}Other pages{% endblock %}
{% block heading %}Other pages{% endblock %}
{% block pageid %}other{% endblock %}

{% block content %}

<div>
<ul>
  <li><a href="{% url "create" %}">Create an event</a></li>
  <li><a href="{% url "reports" %}">Reports page</a></li>
  <li><a href="{% url "feeds" %}">RSS feeds</a></li>
</ul>
</div>

{% endblock %}