config/urls.py
from django.conf import settings

from django.urls import re_path, include

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

# Import feeds
import core.views
from events.feeds import EventFeed, feedview
import events.reports
import events.views
from ligoauth.views import (
    manage_password, ShibLoginView, ShibPostLoginView
)
import search.views

# Django admin auto-discover
admin.autodiscover()

feeds = {
    'latest' : EventFeed
}


urlpatterns = [
    re_path(r'^$', events.views.index, name="home"),
    re_path(r'^navbar_only$', TemplateView.as_view(
        template_name='navbar_only.html'), name="navbar-only"),
    re_path(r'^SPInfo', TemplateView.as_view(template_name='gracedb/spinfo.html'),
         name="spinfo"),
    re_path(r'^SPPrivacy', TemplateView.as_view(
        template_name='gracedb/spprivacy.html'), name="spprivacy"),
    re_path(r'^DiscoveryService', TemplateView.as_view(
        template_name='discovery.html'), name="discovery"),
    re_path(r'^events/', include('events.urls')),
    re_path(r'^superevents/', include('superevents.urls')),
    re_path(r'^alerts/', include('alerts.urls')),
    re_path(r'^feeds/(?P<url>.*)/$', EventFeed()),
    re_path(r'^feeds/$', feedview, name="feeds"),

    re_path(r'^other/$', TemplateView.as_view(template_name='other.html'),
        name='other'),
    re_path(r'^performance/$', events.views.performance, name="performance"),
    re_path(r'^reports/$', events.reports.reports_page_context, name="reports"),
    re_path(r'^latest/$', search.views.latest, name="latest"),
    #(r'^reports/(?P<path>.+)$', 'django.views.static.serve',
    #        {'document_root': settings.LATENCY_REPORT_DEST_DIR}),
    re_path(r'^search/$', search.views.search, name="mainsearch"),

    # Authentication
    re_path(r'^login/$', ShibLoginView.as_view(), name='login'),
    re_path(r'^post-login/$', ShibPostLoginView.as_view(), name='post-login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),

    # Password management
    re_path('^manage-password/$', manage_password, name='manage-password'),

    # API URLs
    re_path(r'^api/', include('api.urls')),
    # Legacy API URLs - must be maintained!
    re_path(r'^apibasic/', include('api.urls', namespace='legacy_apibasic')),
    re_path(r'^apiweb/', include('api.urls', namespace='legacy_apiweb')),

    # Heartbeat URL
    re_path(r'^heartbeat/$', core.views.heartbeat, name='heartbeat'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),

    # Sessions
    re_path(r'^', include('user_sessions.urls', 'user_sessions')),

]

# We don't require settings.DEBUG for django-silk since running unit tests
# by default setings settings.DEBUG to False, unless you use the
# --debug-mode flag
if ('silk' in settings.INSTALLED_APPS):
    # Add django-silk
    urlpatterns = [
        re_path(r'^silk/', include('silk.urls', namespace='silk'))
    ] + urlpatterns

# Add django-debug-toolbar
if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

gracedb/api/urls.py
from django.urls import re_path, include

from .v1 import urls as v1_urls
from .v2 import urls as v2_urls

app_name = 'api'

urlpatterns = [
    re_path(r'^', include((v1_urls, 'default'))),
    re_path(r'^v1/', include((v1_urls, 'v1'))),
    re_path(r'^v2/', include((v2_urls, 'v2'))),
]

gracedb/core/urls.py
# URL utilities

from django.contrib.sites.models import Site


def build_absolute_uri(relative_uri, request=None):
    if request is not None:
        return request.build_absolute_uri(relative_uri)
    else:
        # Assume HTTPS
        domain = Site.objects.get_current().domain
        return 'https://' + domain + relative_uri

# A helper function to return superevent urls from /api/-->/apiweb/
# Note that event files are never exposed to the public and so aren't 
# subject to the same private api vs public apiweb caching schemes
def build_apiweb_uri(relative_uri, request=None):
    absolute_uri = build_absolute_uri(relative_uri, request=request)

    # Return the apiweb url for superevents:
    if '/superevents/' in absolute_uri:
        absolute_uri = absolute_uri.replace('/api/', '/apiweb/')

    return absolute_uri

gracedb/gwtc/urls.py
from django.conf.urls import url, include
from django.urls import path
from superevent.models import Superevent
from superevent import views

app_name = 'gwtc'


# URLs which are nested below a superevent detail
# These are included under a superevent's ID URL prefix (see below)
suburlpatterns = [

    # Superevent detail view
    url(r'^view/$', views.SupereventDetailView.as_view(), name="view"),

    # File list (file detail/download is handled through the API)
    url(r'^files/$', views.SupereventFileList.as_view(), name="file-list"),
]

# Legacy URL patterns - don't really need them, but we use them for the
# convenience of users who may be accustomed to the legacy event URL patterns

# public page url patterns. This needs to go first so django matches 
# the 'public' string before parsing it interprets it as a superevent_id.
# Note to future generations: don't name a GW 'public' or the link breaks.

public_urlpatterns = [
    # The /superevents/public/ url route gets redirected to the 
    # latest observation run.
    path('public/', views.public_alerts_redirect,
        name="public-alerts-redirect"),

    # each run has its own page, but must be in the list of runs that's 
    # in settings/base.py. Otherwise, 404 (this gets defined in the view). 
    # the "obsrun" variable controls which events are shown.
     path('public/<slug:obsrun>/', views.SupereventPublic.as_view(),
         name="public-alerts"),

]
legacy_urlpatterns = public_urlpatterns + [
    # Legacy URLs for superevent detail view
    path('<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview1"),
    path('view/<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview2"),
]

# Full urlpatterns: legacy urls plus suburlpatterns nested under
# superevent_id
urlpatterns = legacy_urlpatterns + [
    path('<str:superevent_id>/',
        include(suburlpatterns)),

]

gracedb/superevents/urls.py
from django.conf.urls import include
from django.urls import path, re_path
from .models import Superevent
from . import views

app_name = 'superevents'


# URLs which are nested below a superevent detail
# These are included under a superevent's ID URL prefix (see below)
suburlpatterns = [

    # Superevent detail view
    re_path(r'^view/$', views.SupereventDetailView.as_view(), name="view"),

    # File list (file detail/download is handled through the API)
    re_path(r'^files/$', views.SupereventFileList.as_view(), name="file-list"),
]

# Legacy URL patterns - don't really need them, but we use them for the
# convenience of users who may be accustomed to the legacy event URL patterns

# public page url patterns. This needs to go first so django matches 
# the 'public' string before parsing it interprets it as a superevent_id.
# Note to future generations: don't name a GW 'public' or the link breaks.

public_urlpatterns = [
    # The /superevents/public/ url route gets redirected to the 
    # latest observation run.
    path('public/', views.public_alerts_redirect,
        name="public-alerts-redirect"),

    # each run has its own page, but must be in the list of runs that's 
    # in settings/base.py. Otherwise, 404 (this gets defined in the view). 
    # the "obsrun" variable controls which events are shown.
     path('public/<slug:obsrun>/', views.SupereventPublic.as_view(),
         name="public-alerts"),

]
legacy_urlpatterns = public_urlpatterns + [
    # Legacy URLs for superevent detail view
    path('<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview1"),
    path('view/<str:superevent_id>/',
        views.SupereventDetailView.as_view(),
        name="legacyview2"),
]

# Full urlpatterns: legacy urls plus suburlpatterns nested under
# superevent_id
urlpatterns = legacy_urlpatterns + [
    path('<str:superevent_id>/',
        include(suburlpatterns)),

]

gracedb/core/models.py
from collections import OrderedDict
import logging

from django.db import models, connection, IntegrityError
from django.db.models import Q, Max
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db.models import QuerySet
from django.forms.models import model_to_dict
from django.utils.translation import gettext_lazy as _

from core.vfile import VersionedFile

# Testing waiting:
from time import sleep
from random import random

DB_SLEEP_FACTOR = settings.DB_SLEEP_FACTOR

# Set up user model
UserModel = get_user_model()

# Set up logger
logger = logging.getLogger(__name__)


class CleanSaveModel(models.Model):
    """Abstract model which automatically runs full_clean() before saving"""

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super(CleanSaveModel, self).save(*args, **kwargs)


class AutoIncrementModel(models.Model):
    """
    An abstract class used as a base for classes which need the
    autoincrementing save method described below.

    AUTO_FIELD: name of field which acts as an autoincrement field.
    AUTO_CONSTRAINTS: tuple of field names to use as a constraint; i.e., the
                      AUTO_FIELD increments relative to the number of rows in
                      the table which have the same values for these fields.
    """
    AUTO_FIELD = None
    AUTO_CONSTRAINTS = None
    max_retries = 5

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):

        # Do a normal save if this is not an insert (i.e., the instance has a
        # primary key already), or if the required fields are not set
        pk_set = self._get_pk_val() is not None
        if (pk_set or (self.AUTO_FIELD is None or
                       self.AUTO_CONSTRAINTS is None)):
            super(AutoIncrementModel, self).save(*args, **kwargs)
        else:
            self.auto_increment_insert(*args, **kwargs)

    def auto_increment_insert(self, *args, **kwargs):
        """

        This has been tested with the following classes:
            EventLog, EMObservation, EMFootprint, EMBBEventLog, VOEvent


        Requires AUTO_FIELD and AUTO_CONSTRAINTS to be defined.
        """

        # Check for the existence of the required fields:
        if not self.AUTO_CONSTRAINTS or not self.AUTO_FIELD:
            raise TypeError('AUTO_CONSTRAINTS or AUTO_FIELD not set.')

        # Check type of self.AUTO_CONSTRAINTS
        if not isinstance(self.AUTO_CONSTRAINTS, (tuple, list)):
            raise TypeError(_('AUTO_CONSTRAINTS should be a tuple or list'))


        # Get some useful information
        meta = self.__class__._meta
        current_class = self.__class__

        # Get model fields, except for primary key field.
        fields = [f for f in meta.local_concrete_fields if not
            isinstance(f, models.fields.AutoField)]

        # Check constraint fields
        f_names = [f.name for f in fields]
        for constraint_field in self.AUTO_CONSTRAINTS:
            if constraint_field not in f_names:
                raise ValueError(_(('Constraint {0} is not a field for '
                    'model {1}').format(constraint_field,
                    current_class.__name__)))

        # Check auto field
        if self.AUTO_FIELD not in f_names:
            raise ValueError(_(('AUTO_FIELD {0} is not a field for '
                'model {1}').format(self.auto_field, self.__class__.__name__)))


        # Set up Q query for multiple constraints. For instance, superevents'
        # base_date_number is constrained by both category and the date. So
        # for example, there can exist S123456a, TS123456a, and MS123456a. The
        # t_0_date is the same, but the category is different. So they each get
        # an "a". 

        const_query = Q()
        for const in self.AUTO_CONSTRAINTS:
            const_query = const_query & Q(**{const: getattr(self, const)})


        # Set AUTO_FIELD to one-plus-the-maximum of the value of AUTO_FIELD
        # in the constained set. Note that since some superevents get removed
        # or other circumstances, the max does not always equal to the number 
        # entries in the set. This caused some db integrity errors in testing.

        # Save object and check constraints. Add ability to retry on the event
        # of DB Integrity errors. 

        number_of_tries = 0
        success = False
        while not success:
            try:
                setattr(self, self.AUTO_FIELD,
                        self.updated_autofield_value(current_class, const_query))
                super(AutoIncrementModel, self).save(*args, **kwargs)
            except (IntegrityError, ValidationError):
                logger.warning("Sleeping to stabilize database. try= {}, object={}".format(number_of_tries, self))
                sleep(DB_SLEEP_FACTOR * random())
                number_of_tries += 1
                if number_of_tries > 6:
                    raise
            else:
                success = True

    def updated_autofield_value(self, current_class, query):
        # get the queryset:
        query_set = current_class.objects.filter(query)
        if query_set:
            return query_set.aggregate(max_val=Max(self.AUTO_FIELD))['max_val'] + 1
        else:
            return 1

    def auto_increment_update(self, update_field_name, constraints=[],
        allow_update_to_nonnull=False):
        """
        UPDATE superevents_superevent SET gw_date_number = (SELECT N FROM (SELECT IFNULL(MAX(gw_date_number),0)+1 as N FROM superevents_superevent WHERE t_0_date='1980-01-06' AND is_gw=1) AS y) WHERE id=41;
        """

        if (not allow_update_to_nonnull and getattr(self, update_field_name)
            is not None):
            raise ValueError(_(('Attempt to update a non-null constrained auto'
                'field for object {0}. Not allowed.').format(self.__str__())))

        # Get current class:
        current_class = self.__class__

        # Set up query based on the constraints:
        query = Q()
        for i in constraints:
            query = query & Q(**{i: getattr(self, i)})

        # get the queryset that meets the constraints:

        qs = current_class.objects.filter(query)

        # Set AUTO_FIELD to one-plus-the-maximum of the value of AUTO_FIELD
        # in the constained set. Note that since some superevents get removed
        # or other circumstances, the max does not always equal to the number
        # entries in the set. This caused some db integrity errors in testing.

        if qs:
            try:
                setattr(self, update_field_name,
                        qs.aggregate(max_val=Max(update_field_name))['max_val'] + 1)
            # Add exception for cases where the update field wasn't
            # initially...updated:
            except TypeError:
                setattr(self, update_field_name, 1)
        else:
            setattr(self, update_field_name, 1)


class LogBase(models.Model):
    """
    Abstract base class for log message-type objects. Concrete derived
    classes will probably want to add a ForeignKey to another model.

    Used in events.EventLog, superevents.Log
    """
    created = models.DateTimeField(auto_now_add=True)
    issuer = models.ForeignKey(UserModel, null=False, on_delete=models.CASCADE)
    filename = models.CharField(max_length=100, default="", blank=True)
    file_version = models.IntegerField(null=True, default=None, blank=True)
    comment = models.TextField(null=False)
    N = models.IntegerField(null=False, editable=False)

    class Meta:
        abstract = True
        ordering = ['-created', '-N']
        indexes = [models.Index(fields=['filename', ])]

    @property
    def versioned_filename(self):
        if self.filename:
            actual_filename = self.filename
            if self.file_version is not None:
                actual_filename += ",{n}".format(n=self.file_version)
        else:
            actual_filename = None
        return actual_filename

    def fileurl(self):
        # Override this on derived classes
        return NotImplemented

    def hasImage(self):
        # XXX hacky
        IMAGE_EXT = ['png', 'gif', 'jpg']
        return (self.filename and self.filename[-3:].lower() in IMAGE_EXT)

    @staticmethod
    def split_versioned_filename(versioned_name):
        filename, version = VersionedFile.split_versioned_name(versioned_name)
        return filename, version


class m2mThroughBase(models.Model):
    """
    Abstract base class which is useful for providing "through" access for a
    many-to-many relationship and recording the relationship creator and
    creation time.
    """
    creator = models.ForeignKey(UserModel, null=False, related_name=
        '%(app_label)s_%(class)s_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

gracedb/api/v2/events/views.py
from ...v1.events.views import *

gracedb/api/v2/main/views.py
from ...v1.main.views import *

gracedb/api/v2/superevents/views.py
from ...v1.superevents.views import *

gracedb/templates/gracedb/eel_detail.html
{% extends "base.html" %}

{% block title %}Electromagnetic Bulletin Board{% endblock %}
{% block heading %}EMBBEventLog Detail{% endblock %}
{% block pageid %}eel_detail{% endblock %}

{% block content %}

<div class="text">

<p>
This will be the eel detail page.
</p>

</div>

{% endblock %}

gracedb/templates/gracedb/event_detail.html
{% extends "base.html" %}
{% load timeutil %}
{% load mediaviews %}
{% load scientific %}
{% load sanitize_html %}
{% load logtags %}
{% block title %} {{ object.graceid }} {% endblock %}
{% block heading %}{% endblock %}
{% block bodyattrs %}class="tundra eventDetail"{% endblock %}

{% block jscript %}
{% load static %}
<link rel="stylesheet" href="{% static "css/labeltips.css" %}" />

<script type="text/javascript" class="init">
  $(document).ready(function () {
    $('#event-neighbors').DataTable({
      paging:false,
      searching:false,
      info:false,
      order: [[4, 'desc']],
    });
  });
</script>


{% endblock %}

{% block content %}
<div class='row'>
  <div class='col-md-2'>
    <div class="sticky-top" style="top: 75px;">
      <nav id="toc" data-toggle="toc"></nav>
    </div>
  </div>
  <div class='col-md overflow-auto'>

    {% if object.offline %}
    <div style="text-align: center;">
      <div style="font-weight: 300; color: red; font-size:xx-large">OFFLINE EVENT</div>
    </div>
    <br>
    {% endif %}

    <h2> {{ object.graceid }} </h2>
    <hr style="width:250px; text-align:left; margin-left:0;">


    <p>{{ message }}</p>

    {% if 'lvem_view' not in request.path %}

    <!-- Here is a section for the control room operator signoff -->
    {% if operator_signoff_authorized and operator_signoff_active %}
    <div class="signoff-area">
      <h3> {{signoff_instrument}} Operator Signoff </h3>
      <p> You are seeing this section because you've connected from a machine that, 
      according to our records, is in the {{signoff_instrument}} control room. 
      {% if operator_signoff_object %}
      This event has already been signed off on.
      Use the form below if you wish to edit or delete the record. </p>
      <form action="{% url "modify_signoff" object.graceid %}" method="post">
        <table>
          <tr><th><label for="id_status">Status:</label></th><td><select id="id_status" name="status">
                <option value="">---------</option>
                {% if operator_signoff_object.status == "OK" %}
                <option value="OK" selected="selected">OKAY</option>
                <option value="NO">NOT OKAY</option>
                {% else %}
                <option value="OK">OKAY</option>
                <option value="NO" selected="selected">NOT OKAY</option>
                {% endif %}
              </select></td></tr>
              <tr><th><label for="id_comment">Comment:</label></th><td>
                  <textarea cols="40" id="id_comment" name="comment" rows="10">{{operator_signoff_object.comment}}</textarea></td></tr>
              <input type="hidden" name="signoff_type" value="operator">
              <input type="hidden" name="action" value="edit">
              <tr> <th> Delete </th> <td> <input type="checkbox" name="delete" value="true"> </td> </tr>
              <tr> <td></td> <td> <input type="submit" value="Submit" class="searchButtonClass"> </td> </tr>
        </table>
      </form>

      {% else %}
      This event still requires operator signoff. </p> 
      <p> Please answer the following (and optionally enter a comment): At the time of the 
      {% if signoff_instrument == 'H1' %}
      event ({{ object.gpstime|gpsdate_tz:"lho" }}),
      {% elif signoff_instrument == 'L1' %}
      event ({{ object.gpstime|gpsdate_tz:"llo" }}),
      {% elif signoff_instrument == 'V1' %}
      event ({{ object.gpstime|gpsdate_tz:"virgo" }}),
      {% else %}
      event,
      {% endif %}
      was the operating status of the detector basically okay, or not? </p>
      <form action="{% url "modify_signoff" object.graceid %}" method="post">
        <table>
          {{ signoff_form.as_table }}
          <input type="hidden" name="signoff_type" value="operator">
          <input type="hidden" name="action" value="create">
          <tr> <td></td> <td> <input type="submit" value="Submit" class="searchButtonClass"> </td> </tr>
        </table>
      </form>
      {% endif %}
    </div>
    {% endif %}

    <!-- Here is a section for the EM advocate signoffs. -->
    <!-- XXX So much ugliness here. Is there a way to do this with the JS? -->
    {% if advocate_signoff_authorized and advocate_signoff_active %}
    <div class="signoff-area">
      <h3> Advocate Signoff </h3>
      <p> You are seeing this section because you're a designated EM followup 
      advocate.
      {% if advocate_signoff_object %}
      This event has already been signed off on.
      Use the form below if you wish to edit or delete the record. </p>
      <form action="{% url "modify_signoff" object.graceid %}" method="post">
        <table>
          <tr><th><label for="id_status">Status:</label></th><td><select id="id_status" name="status">
                <option value="">---------</option>
                {% if advocate_signoff_object.status == "OK" %}
                <option value="OK" selected="selected">OKAY</option>
                <option value="NO">NOT OKAY</option>
                {% else %}
                <option value="OK">OKAY</option>
                <option value="NO" selected="selected">NOT OKAY</option>
                {% endif %}
              </select></td></tr>
              <tr><th><label for="id_comment">Comment:</label></th><td>
                  <textarea cols="40" id="id_comment" name="comment" rows="10">{{advocate_signoff_object.comment}}</textarea></td></tr>
              <input type="hidden" name="signoff_type" value="advocate">
              <input type="hidden" name="action" value="edit">
              <tr> <th> Delete </th> <td> <input type="checkbox" name="delete" value="true"> </td> </tr>
              <tr> <td></td> <td> <input type="submit" value="Submit" class="searchButtonClass"> </td> </tr>
        </table>
      </form>

      {% else %}
      This event still requires EM Followup advocate signoff. </p> 
      <form action="{% url "modify_signoff" object.graceid %}" method="post">
        <table>
          {{ signoff_form.as_table }}
          <input type="hidden" name="signoff_type" value="advocate">
          <input type="hidden" name="action" value="create">
          <tr> <td></td> <td> <input type="submit" value="Submit" class="searchButtonClass"> </td> </tr>
        </table>
      </form>
      {% endif %}
    </div>
    {% endif %}

    {% endif %} {# lvem_view not in request.path #}


    {% block basic_info %}
    <div class="row my-3 justify-content-center">
      <div class="col-md-10">

        <table class="table-hover table-condensed table-resp-gracedb shadow p-3 mb-5 rounded">
          <thead>
            <tr>
              <th colspan="2"><h3>Basic Event Information</h3></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>UID</td>
              <td>{{ object.graceid }}</td>
            </tr>
            <tr>
              <td>Labels</td>
              <td>
                {% if object.labelling_set.all %}
                {% for labelling in object.labelling_set.all %}
                <span style="color: {{labelling.label.defaultColor}};" class="label"
                                                                       data-toggle="tooltip"
                                                                       data-placement="top"
                                                                       data-html="true"
                                                                       title="<em>{{labelling.label.description}}</em><br>
                                                                       <b>Added by:</b> {{labelling.creator.get_full_name}}<br>
                                                                       <b>Added:</b> {{labelling.created}}">
                                                                       {{ labelling.label.name }}</span>
                {% endfor %}
                {% else %}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>Group</td>
              <td>{{ object.group.name }} </td>
            </tr>
            <tr>
              <td>Pipeline</td>
              <td>{{ object.pipeline.name }} </td>
            </tr>
            <tr>
              <td>Search</td>
              <td>{{ object.search.name }} </td>
            </tr>
            <tr>
              <td>Instruments</td>
              <td>{{ object.instruments }}</td>
            </tr>
            <tr>
              <td>
                {{ "gps"|timeselect:"gps" }}
              </td>
              <td>{% if object.gpstime %}
                {{ object.gpstime|multiTime:"gps" }}
                {% endif %}</td>
            </tr>
            <tr>
              <td>FAR (Hz)</td>
              {# NOTE: XXX Using event_far so it can be floored for external users. #}
              <td>{% if far_is_upper_limit %} &lt; {% endif %}{{ display_far|scientific }}</td>
            </tr>
            <tr>
              <td>FAR (yr<sup>-1</sup>)</td>
              <td>{% if far_is_upper_limit %} &lt; {% endif %}{{ display_far_yr }}</td>
            </tr>
            <tr>
              <td>Latency (s)</td>
              <td>{{ object.reporting_latency|floatformat:"-3" }} </td>
            </tr>
            <tr>
              <td>Links</td>
              <td><a href="{{ object.weburl }}">Data</a></td>
            </tr>
            <tr>
              <td>
                {{ "submitted"|timeselect:"utc" }}
              </td>
              <td>{{ object.created|multiTime:"submitted" }}</td>
            </tr>
            {% if object.superevent %}
            <tr>
              <td>Superevent</td>
              <td><a href="{{ object.superevent.get_web_url }}">{{ object.superevent.superevent_id }}</a></td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
    {% endblock %}

    {% if user_is_external %}
    {# Analysis-specific attributes which can be exposed to external partners #}
    {% block external_analysis_specific %}
    {# Empty by default #}
    {% endblock %}
    {% else %}
    {# Analysis-specific attributes #}
    {% block analysis_specific %}
    {# This block is empty in the base event_detail template #}
    {% endblock %}
    {% endif %}

    {# Neighbors #}

<script>
document.addEventListener('DOMContentLoaded', (event) => {
    document.getElementById('changeBtn').addEventListener('click', function(event) {
        event.preventDefault();
        let delta = document.getElementById('rangeBox').value;
        if (delta.match(/^-?\d+$/) == null & delta.match(/^[-+]?\d+,[-+]?\d+$/) == null) {
          alert("Bad neighborhood specified.")
          return;
        }

        var neighborUrlPattern = "{% url "neighbors" object.graceid "000" %}"
        var neighbor_div = document.getElementById("gdb-table-neighbors");
        neighborUrl = neighborUrlPattern.replace("000", delta);

        // Create a new XMLHttpRequest object
        let xhr = new XMLHttpRequest();
        
        // Configure it: GET-request for the URL
        xhr.open('GET', neighborUrl, true);

        // Define what happens on successful data submission
        xhr.onload = function() {
            if (xhr.status >= 200 && xhr.status < 300) {
                //alert('Data submitted successfully: ' + xhr.responseText);
                document.getElementById('gdb-table-neighbors').innerHTML = xhr.responseText;
            } else {
                alert('Failed to submit data: ' + xhr.statusText);
            }
        };

        // Define what happens in case of error
        xhr.onerror = function() {
            alert('Request failed');
        };

        // Send the request
        xhr.send();
    });
});
</script>

    <h2> Neighbors </h2>
    <hr style="width:250px; text-align:left; margin-left:0;">

    <div class="row my-3 justify-content-center">
      <div class="col-md-10">
<form class="form-inline">
  Neighbor Window:
  <div class="form-group mx-sm-3 mb-2">
              <input class="form-control form-control-sm"
                     type="text"
                     id="rangeBox" name="rangeBox"
                     value="-5,+5">
  </div>
<button type="submit"
        class="btn btn-secondary btn-sm mb-2"
        id="changeBtn">Change Range</button>
</form>
<br>
        <div id="gdb-table-neighbors">
        {% include "gracedb/neighbors_frag.html" %}
        </div>

      </div>
    </div>


    {% if log_too_big %}
    <center>
      <div class="alert alert-danger" role="alert" style="max-width:750px;">
        Event {{ object.graceid }}'s log length ({{ log_length }} entries) exceeds the 
        maximum of {{ max_log }}, and has been quarantined. Please contact an
        administrator for assistance in viewing this event.
      </div>
    </center>

    {% else %}
    {% include "gracedb/log_entry_details.html" %}
    {% endif %}
  </div>
</div>

{% endblock %}

gracedb/templates/gracedb/spinfo.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block heading %}GraceDB &mdash; Service Provider Information{% endblock %}
{% block pageid %}SPInfo{% endblock %}

{% block content %}

<div class="text">

<p>
GraceDB organizes candidate events from gravitational-wave searches and provides an
environment to record information about follow-ups.
</p>

</div>

{% endblock %}